### ISSUE TITLE
can't load HTSLib Shared library despite it being on the $PATH; no config file to modify

### ISSUE THREAD

**Issue by warrenmcg** [zhqingit/giremi#1]
Hi,

I'm excited to use your tool on some of my data. However, I have an error that I can't figure out how to solve.

Here is the output I see:

```
$ ./giremi
giremi: error while loading shared libraries: libhts.so.1: cannot open shared object file: No such file or directory
```

However, my $PATH variable includes the location of this file:

```
$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/lib
$ ls /usr/local/lib/libhts.so.1
/usr/local/lib/libhtso.so.1
```

Your README.md says `Please make sure your dynamic library path in your configuration file includes the directory in which HTSlib is installed`, but I don't see what configuration file I'm supposed to be modifying, and I don't know how to recompile the giremi script from source.

Let me know how I can solve this issue.

Thanks,
Warren

**Comment by zhqingit** [comment]
Hi Warren,

The library directory should be included in this variable: $LD_LIBRARY_PATH
not the $PATH.

Let me know if you have other questions.

Best,
Qing

2015-09-03 18:10 GMT-07:00 Warren McGee notifications@github.com:

**Comment by warrenmcg** [comment]
That worked! Thank you! You should probably update your installation instructions to let users know that `$LD_LIBRARY_PATH` is the variable that needs to be set.

**Comment by zhqingit** [comment]
Thanks, Warren.

Best,
Qing

2015-09-04 9:09 GMT-07:00 Warren McGee notifications@github.com:
