### ISSUE TITLE
Homozygous SNV's

### ISSUE THREAD

**Issue by steveners** [zhqingit/giremi#36]
Hello! I have some question: in previous issues you reccomend to remove homozygous SNV's from SNV list. Now I have a question: should I remove homozygous **SNV's** or I should remove homozygous **SNP's** known from dbSNP? I found in article that this requirement is necessary only for GLM stage: you train this model assuming that all SNP's from list are heterozygous. So why should I remove all homozygous **SNV's**? Thank you!

**Comment by zhqingit** [comment]
Hi Stevener,

I suggest to remove all homozygous SNVs. Specifically, the SNVs
with extreme frequencies. The MI distribution is also affected by the
homozygous SNVs.  Thanks.

Best,
Qing

2017-06-20 14:00 GMT-07:00 steveners <notifications@github.com>:

**Comment by steveners** [comment]
Hi Qing,

Thank you! It is just strange that there is no information about it in paper.
