### ISSUE TITLE
Error while running giremi.r

### ISSUE THREAD

**Issue by narangsign** [zhqingit/giremi#8]
Hi Qing,

I am also getting error while running giremi.r:

Error in data.frame(..., check.names = FALSE) : 
  arguments imply differing number of rows: 0, 1
Calls: cbind -> cbind -> data.frame
Execution halted

I have attached my giremi output files.  Please help!

[giremi_output.Rout.txt](https://github.com/zhqingit/giremi/files/173348/giremi_output.Rout.txt)

[giremi_output.zip](https://github.com/zhqingit/giremi/files/173350/giremi_output.zip)

**Comment by zhqingit** [comment]
Hi,

Your SNV list file includes only the homozygous SNPs.

Best,
Qing

2016-03-14 23:12 GMT-07:00 Vipin notifications@github.com:

**Comment by narangsign** [comment]
Hi Qing,

Thanks for your prompt reply.  Yes, most SNPs in my data are homozygous but a few are not.  Will giremi not work for this type of dataset?

As others have also requested in the forum, can you please provide a set of sample input files for reference.  It will help us a lot to check our data.

Best,

**Comment by zhqingit** [comment]
HI, 

The homozygous SNPs can cause the MI calculation and allelic ratio estimation problems. Please remove them.

Please find the sample file in this issue: #4

Best,
Qing

**Comment by narangsign** [comment]
Thanks, my question is answered.  I am closing this thread.
